import { Inter } from "next/font/google";
import "./globals.css";

import { Nunito } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Modal from "@/components/modals/Modal";
import RegisterModal from "@/components/modals/RegisterModal";
import ToastProvider from "@/providers/ToastProvider";
import LoginModal from "@/components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "@/components/modals/RentModal";
import SearchModal from "@/components/modals/SearchModal";
import Container from "@/components/Container";
Navbar;
export const metadata = {
	title: "Airbnb Clone",
	description: "Generated by create next app",
};

const font = Nunito({
	subsets: ["latin"],
});

export default async function RootLayout({ children }) {
	const currentUser = await getCurrentUser();
	return (
		<html lang="en">
			<body className={font.className}>
				{/* <Modal isOpen={true} title={" Login Modal"} actionLabel={"Submit"} SecondaryActionLabel={"Submit"}/> */}
				<SearchModal />
				<RegisterModal />
				<LoginModal />
				<ToastProvider />
				<RentModal />
				<Navbar currentUser={currentUser} />
				<Container>

				<div className=" ">{children}</div>
				</Container>
			</body>
		</html>
	);
}
